swagger: '2.0'
info:
  version: "0.0.2"
  title: XSS
  description: <s>sssssssssssssssssssssssss</s>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response<s>sssssssssssssssssssssssss</s>
