swagger: '2.0'
info:
  version: "0.0.1"
  title: XSS Vulnerable
  description: <img src="http://bxss.com">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
